---
- name: 'Prepare an Ansible host for Github Actions'
  hosts: localhost
  tasks:
    - name: 'Install tar for delegated to localhost tasks'
      community.general.apk:
        name: tar
        update_cache: true
      when: ansible_os_family == 'Alpine'

- name: 'Converge'
  hosts: all
  vars:
    locale: 'en_US.UTF-8'
    postgres_exporter_tls_server_config:
      cert_file: '/usr/local/etc/ssl/postgres_exporter.cert'
      key_file: '/usr/local/etc/ssl/postgres_exporter.key'
    postgres_exporter_basic_auth_users:
      newuser1: newpassword1

  pre_tasks:
    - name: 'Update APT cache'
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: 'Set database locale if using RedHat 8'
      ansible.builtin.set_fact:
        locale: 'C.UTF-8'
      when:
        - ansible_os_family == 'RedHat' and
          ansible_distribution_major_version == '8'

    - name: 'Create certificate directories'
      ansible.builtin.file:
        path: '{{ postgres_exporter_tls_server_config.cert_file | dirname }}'
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: 'Copy certificate and key'
      ansible.builtin.copy:
        src: '{{ cert.src }}'
        dest: '{{ cert.dest }}'
        mode: 0644
      loop:
        - src: '/tmp/certificate.cert'
          dest: '{{ postgres_exporter_tls_server_config.cert_file }}'
        - src: '/tmp/certificate.key'
          dest: '{{ postgres_exporter_tls_server_config.key_file }}'
      loop_control:
        loop_var: cert

  roles:
    - role: geerlingguy.postgresql
      postgresql_users:
        - name: 'molecule'
          password: 'molecule'
          role_attr_flags: SUPERUSER
      postgresql_databases:
        - name: 'molecule'
          lc_collate: '{{ locale }}'
          lc_ctype: '{{ locale }}'
          encoding: 'UTF-8'
          template: 'template0'
          owner: 'molecule'
    - role: antmelekhin.postgres_exporter
