---
- hosts: all
  tasks:
    - name: Update package cache (Debian, Ubuntu)
      become: true
      apt:
        update_cache: true
      when: (ansible_os_family | lower) == 'debian'
      ignore_errors: true  # Necessary as snapshot repos expire

    - name: Update package cache (Redhat)
      become: true
      yum:
        update_cache: true
      when:
        - (ansible_os_family | lower) == 'redhat'
      ignore_errors: true  # Necessary as snapshot repos expire

    - name: Create man directories
      become: true
      file:
        path: "{{ item }}"
        owner: root
        group: root
        mode: "u=rwx,go=rx"
        state: directory
      loop:
        - /usr/share/man/man1
        - /usr/share/man/man7
      when: (ansible_distribution | lower) == 'debian'

- hosts: all
  roles:
    - geerlingguy.postgresql
