---

- name: Checking ansible version
  ansible.builtin.fail:
    msg: "Ansible version must be {{ minimal_ansible_version }} or higher"
  delegate_to: localhost
  when:
    - ansible_version.full is version(minimal_ansible_version, '<')

- name: Checking Linux distribution
  ansible.builtin.fail:
    msg: "{{ ansible_distribution }} is not supported"
  when: ansible_distribution not in os_valid_distributions

- name: Checking version of OS Linux
  ansible.builtin.fail:
    msg: "{{ ansible_distribution_version }} of {{ ansible_distribution }} is not supported"
  when: ansible_distribution_version is version_compare(os_minimum_versions[ansible_distribution], '<')

- name: Perform pre-checks for timescaledb
  ansible.builtin.import_tasks: timescaledb.yml
  when:
    - enable_timescale is defined
    - enable_timescale | bool
    - inventory_hostname in groups['postgres_cluster']

- name: Perform pre-checks for pgbouncer
  ansible.builtin.import_tasks: pgbouncer.yml
  when:
    - pgbouncer_install is defined
    - pgbouncer_install | bool
    - inventory_hostname in groups['postgres_cluster']

- name: Perform pre-checks for patroni
  ansible.builtin.import_tasks: patroni.yml
  when:
    - inventory_hostname in groups['postgres_cluster']

- name: Perform pre-checks for pgbackrest
  ansible.builtin.import_tasks: pgbackrest.yml
  when:
    - pgbackrest_install is defined
    - pgbackrest_install | bool
    - inventory_hostname in groups['postgres_cluster']

- name: Perform pre-checks for WAL-G
  ansible.builtin.import_tasks: wal_g.yml
  when:
    - wal_g_install is defined
    - wal_g_install | bool
    - inventory_hostname in groups['postgres_cluster']
