---
_postgres_exporter_os: 'linux'

_postgres_exporter_architecture_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

_postgres_exporter_architecture: '{{ _postgres_exporter_architecture_map[ansible_architecture] | default(ansible_architecture) }}'

_postgres_exporter_install_path: '/usr/local/bin'
_postgres_exporter_config_path: '/usr/local/etc'

_postgres_exporter_data_source_name: 'user=postgres host=/var/run/postgresql/ sslmode=disable'
