---
- name: 'Windows | Set an environment variable for Postgres Exporter'
  ansible.windows.win_environment:
    level: machine
    name: 'DATA_SOURCE_NAME'
    value: '{{ postgres_exporter_data_source_name }}'
    state: present
  notify: 'Windows | Restart Postgres Exporter scheduled task'

- name: 'Windows | Configure startup script for Postgres Exporter'
  ansible.windows.win_template:
    src: 'Start-PostgresExporter.ps1.j2'
    dest: '{{ postgres_exporter_install_path }}\Start-PostgresExporter.ps1'
  notify: 'Windows | Restart Postgres Exporter scheduled task'

- name: 'Windows | Configure web config file for Postgres Exporter'
  ansible.windows.win_template:
    src: 'web_config.yaml.j2'
    dest: '{{ postgres_exporter_config_path }}\web_config.yaml'
  notify: 'Windows | Restart Postgres Exporter scheduled task'
  when:
    - postgres_exporter_tls_server_config | length or
      postgres_exporter_http_server_config | length or
      postgres_exporter_basic_auth_users | length

- name: 'Windows | Ensure scheduled task for Postgres Exporter is enabled at boot'
  community.windows.win_scheduled_task:
    name: 'Postgres Exporter'
    description: 'Prometheus exporter for Postgres server metrics.'
    actions:
      - path: '%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe'
        arguments: '-ExecutionPolicy ByPass -File "{{ postgres_exporter_install_path }}\Start-PostgresExporter.ps1"'
    triggers:
      - type: 'boot'
    execution_time_limit: 'PT0S'
    username: 'SYSTEM'
    enabled: true
    state: present
  notify: 'Windows | Restart Postgres Exporter scheduled task'

- name: 'Windows | Ensure firewall rule for Postgres Exporter is allow'
  community.windows.win_firewall_rule:
    name: 'Postgres Exporter'
    description: 'Inbound rule for Postgres Exporter'
    program: '{{ postgres_exporter_install_path }}\postgres_exporter.exe'
    localport: '{{ postgres_exporter_web_listen_port }}'
    action: allow
    direction: in
    protocol: tcp
    profiles: 'domain,private,public'
    enabled: true
    state: present
