---
postgres_exporter_user: postgres
postgres_exporter_user_manage: true
postgres_exporter_group: "{{ postgres_exporter_user }}"
postgres_exporter_group_manage: true
postgres_exporter_home: "/var/lib/postgres_exporter"
postgres_exporter_home_manage: true
