replicaCount: 2

image:
  repository: ghcr.io/ldest/sre-course/api
  pullPolicy: IfNotPresent
  tag: "c4f3862"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

autoscaling: {}

serviceAccount: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: weather-app.api
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
